// <auto-generated />
namespace testuser.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class campo_required_Archivo_tblhistorial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(campo_required_Archivo_tblhistorial));
        
        string IMigrationMetadata.Id
        {
            get { return "201904011706188_campo_required_Archivo_tblhistorial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
